project_id = "mzpweuuvyuaawpttoqkn"

[functions.preset-recommendations]
verify_jwt = false

[functions.send-auto-archive-notification]
verify_jwt = false

[functions.send-low-stock-alert]
verify_jwt = false

[functions.check-low-stock]
verify_jwt = false